import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { Overlay } from '../components/Overlay';
import { PageHeader } from '../components/PageHeader';
import { SimpleStatusPill } from '../components/StatusPill';
import { useAdminUsers } from '../api/queries';
export function AdminUsersPage(){const data=useAdminUsers().data??[];const[inviteOpen,setInviteOpen]=useState(false);return <div className="page"><PageHeader kicker="RBAC" title="Пользователи" description="Доступ к данным определяется ролью и организационной областью; frontend скрывает недоступные действия, backend обязан повторно проверять права." actions={<button type="button" className="btn btn--primary" onClick={()=>setInviteOpen(true)}><Icon name="plus"/>Пригласить</button>}/><div className="registry-card desktop-table-wrap"><table className="data-table data-table--admin"><thead><tr><th>Пользователь</th><th>Роль</th><th>Организация / филиал</th><th>2FA</th><th>Последняя активность</th><th>Статус</th><th></th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong className="table-main">{x.name}</strong><span className="table-muted table-muted--block">{x.email}</span></td><td><span className="table-main">{x.role}</span></td><td><span className="table-main">{x.organization}<br/><small>{x.branch}</small></span></td><td><SimpleStatusPill label={x.twoFactor?'Включена':'Нет'} tone={x.twoFactor?'success':'warning'}/></td><td><span className="table-muted">{x.lastSeen}</span></td><td><SimpleStatusPill label={x.status==='active'?'Активен':x.status==='blocked'?'Заблокирован':'Приглашён'} tone={x.status==='active'?'success':x.status==='blocked'?'danger':'info'}/></td><td><Link className="table-action-link" to={`/admin/users/${x.id}/access`}>Доступ <Icon name="chevron"/></Link></td></tr>)}</tbody></table></div><div className="mobile-card-list admin-mobile-list">{data.map(x=><Link to={`/admin/users/${x.id}/access`} className="mobile-entity-card mobile-entity-card--link" key={x.id}><div className="mobile-entity-card__head"><div><span>{x.email}</span><strong>{x.name}</strong></div><SimpleStatusPill label={x.status==='active'?'Активен':'Проверить'} tone={x.status==='active'?'success':'warning'}/></div><div className="mobile-entity-card__rows"><span><b>Роль</b><em>{x.role}</em></span><span><b>Область</b><em>{x.branch}</em></span><span><b>2FA</b><em>{x.twoFactor?'Включена':'Не включена'}</em></span></div><span className="mobile-entity-card__open">Настроить доступ <Icon name="chevron"/></span></Link>)}</div>
<Overlay open={inviteOpen} onClose={()=>setInviteOpen(false)} title="Пригласить пользователя" description="Приглашение создаёт учётную запись; права назначаются отдельно и проверяются backend." kicker="Пользователь" presentation="sheet" footer={<><button type="button" className="btn btn--ghost" onClick={()=>setInviteOpen(false)}>Отмена</button><button type="button" className="btn btn--primary" onClick={()=>setInviteOpen(false)}>Отправить приглашение</button></>}><div className="overlay-form-grid"><label className="is-full"><span>Email</span><input type="email" placeholder="name@company.ru"/></label><label><span>Роль</span><select><option>Логист</option><option>Бухгалтер</option><option>Руководитель</option><option>Администратор</option></select></label><label><span>Филиал</span><select><option>Основная организация</option><option>Москва</option><option>Казань</option></select></label></div></Overlay></div>}
