import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { PageHeader } from '../components/PageHeader';
import { Overlay } from '../components/Overlay';
import { SemanticStatusText } from '../components/StatusPill';

export function AdminSecurityPage(){
  const [policyOpen,setPolicyOpen]=useState(false);
  const [twoFactor,setTwoFactor]=useState(true);
  const [sso,setSso]=useState(true);
  return <div className="page"><PageHeader kicker="Безопасность" title="Политика доступа" description="Аутентификация, 2FA, SSO и ограничения сессии. Секреты и закрытые ключи никогда не отображаются в браузере." actions={<button type="button" className="btn btn--primary" onClick={()=>setPolicyOpen(true)}><Icon name="settings"/>Изменить политику</button>}/>
    <section className="security-policy-grid">
      <article className="panel security-policy-card"><div className="security-policy-card__head"><span className="security-policy-card__icon"><Icon name="shield"/></span><div><span className="eyebrow">Аутентификация</span><h2>2FA для критичных ролей</h2></div><SemanticStatusText label={twoFactor?'Обязательно':'По настройке'} tone={twoFactor?'success':'warning'}/></div><p>Администраторы, бухгалтеры, подписанты и пользователи с финансовыми данными проходят второй фактор.</p><div className="security-policy-facts"><span><b>Пароль</b><strong>Сложность включена</strong></span><span><b>Блокировка</b><strong>После серии ошибок</strong></span></div></article>
      <article className="panel security-policy-card"><div className="security-policy-card__head"><span className="security-policy-card__icon"><Icon name="key"/></span><div><span className="eyebrow">Корпоративный вход</span><h2>OIDC / SAML SSO</h2></div><SemanticStatusText label={sso?'Подключено':'Выключено'} tone={sso?'success':'neutral'}/></div><p>Frontend инициирует вход, но токены и client secret остаются только в защищённом backend-контуре.</p><div className="security-policy-facts"><span><b>Провайдер</b><strong>TMS Corporate SSO</strong></span><span><b>Среда</b><strong>Production</strong></span></div></article>
      <article className="panel security-policy-card"><div className="security-policy-card__head"><span className="security-policy-card__icon"><Icon name="clock"/></span><div><span className="eyebrow">Сессия</span><h2>Ограничение неактивности</h2></div><SemanticStatusText label="30 минут" tone="info"/></div><p>Чувствительные разделы завершают сессию после периода неактивности согласно политике организации.</p><div className="security-policy-facts"><span><b>Повторный вход</b><strong>С 2FA при необходимости</strong></span><span><b>Scope</b><strong>Роль + организация</strong></span></div></article>
      <article className="panel security-policy-card"><div className="security-policy-card__head"><span className="security-policy-card__icon"><Icon name="link"/></span><div><span className="eyebrow">Интеграции</span><h2>Секреты вне frontend</h2></div><SemanticStatusText label="Защищено" tone="success"/></div><p>API keys, client secret, токены, пароли и закрытые ключи не являются frontend DTO и не попадают в логи интерфейса.</p><Link className="text-link" to="/integrations">Открыть интеграции <Icon name="arrow"/></Link></article>
    </section>
    <section className="panel security-note-panel"><span className="eyebrow">Контроль</span><h2>Права проверяет backend</h2><p>Скрытие раздела или кнопки во frontend улучшает UX, но не является границей безопасности. Каждый mutation и read endpoint повторно проверяет роль, организацию и объект доступа.</p><Link className="btn btn--secondary" to="/admin/audit">Открыть аудит <Icon name="arrow"/></Link></section>
    <Overlay open={policyOpen} onClose={()=>setPolicyOpen(false)} title="Политика доступа" description="Prototype-state показывает будущую форму. Реальные изменения должны сохраняться отдельным защищённым backend mutation и попадать в аудит." kicker="Безопасность" presentation="sheet" footer={<><button type="button" className="btn btn--ghost" onClick={()=>setPolicyOpen(false)}>Отмена</button><button type="button" className="btn btn--primary" onClick={()=>setPolicyOpen(false)}>Сохранить</button></>}><div className="security-toggle-list"><label><span><strong>2FA для критичных ролей</strong><small>Администраторы, бухгалтеры, подписанты и финансовые данные</small></span><input type="checkbox" checked={twoFactor} onChange={e=>setTwoFactor(e.target.checked)}/></label><label><span><strong>Корпоративный SSO</strong><small>OIDC/SAML, если провайдер организации настроен</small></span><input type="checkbox" checked={sso} onChange={e=>setSso(e.target.checked)}/></label><label><span><strong>Таймаут чувствительных разделов</strong><small>По умолчанию 30 минут</small></span><select defaultValue="30"><option value="15">15 минут</option><option value="30">30 минут</option><option value="60">60 минут</option></select></label></div></Overlay>
  </div>;
}
