import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { PageHeader } from '../components/PageHeader';
import { useCounterpartiesDirectory, useTrips } from '../api/queries';
export function EdoNewPage(){
 const trips=useTrips().data??[]; const counterparties=useCounterpartiesDirectory().data??[]; const navigate=useNavigate(); const [saved,setSaved]=useState(false);
 return <div className="page form-page"><PageHeader kicker="Исходящий документ" title="Новый документ ЭДО" description="Создайте документ из данных рейса или вручную. Маршрут согласования назначается до отправки." actions={<Link to="/edo" className="btn btn--ghost"><Icon name="back"/>К ЭДО</Link>}/><div className="form-layout"><form className="panel structured-form" onSubmit={e=>e.preventDefault()}><section className="form-section"><div className="form-section__head"><span>01</span><div><h2>Документ</h2><p>Тип и источник данных.</p></div></div><div className="form-grid"><label><span>Тип</span><select defaultValue="УПД"><option>УПД</option><option>Акт</option><option>Счёт</option><option>Договор</option></select></label><label><span>Источник</span><select><option>Из рейса</option><option>Вручную</option><option>Из шаблона</option></select></label><label className="form-span-2"><span>Рейс</span><select>{trips.map(t=><option key={t.id}>{t.number} · {t.counterparty}</option>)}</select></label></div></section><section className="form-section"><div className="form-section__head"><span>02</span><div><h2>Стороны и сумма</h2><p>Проверяем контрагента до начала согласования.</p></div></div><div className="form-grid"><label className="form-span-2"><span>Контрагент</span><select>{counterparties.map(c=><option key={c.id}>{c.name} · ИНН {c.inn}</option>)}</select></label><label><span>Сумма, ₽</span><input type="number" defaultValue="125000"/></label><label><span>Маршрут согласования</span><select><option>УПД · стандарт</option><option>Акт · перевозка</option></select></label><label className="form-span-2"><span>Комментарий</span><textarea rows={3}/></label></div></section><div className="form-actions"><button className="btn btn--ghost" type="button" onClick={()=>setSaved(true)}>{saved?'Черновик сохранён':'Сохранить черновик'}</button><button className="btn btn--primary" type="button" onClick={()=>navigate('/edo/edo-251')}><Icon name="check"/>Создать документ</button></div></form><aside className="panel form-summary"><span className="eyebrow">Согласование</span><h2>Перед отправкой</h2><div className="vertical-check-list"><span><Icon name="check"/>Реквизиты заполнены</span><span><Icon name="check"/>Контрагент определён</span><span><Icon name="clock"/>Подписант назначается маршрутом</span></div><p>Отправка через Saby выполняется асинхронно — внешний запрос не должен блокировать страницу.</p></aside></div></div>
}
