import { Link } from 'react-router-dom';
import { Icon } from '../components/Icon';
import { MetricCard } from '../components/MetricCard';
import { PageHeader } from '../components/PageHeader';
import { SemanticStatusText } from '../components/StatusPill';
import { useTechnicalInspections } from '../api/queries';

function statusMeta(status:string): [string, 'success'|'warning'|'danger'] { return status==='ready'?['Готово','success']:status==='attention'?['Проверить','warning']:['Выпуск запрещён','danger']; }
export function MechanicHomePage(){const items=useTechnicalInspections().data??[];const ready=items.filter(x=>x.status==='ready').length;const blocked=items.filter(x=>x.status==='blocked').length;return <div className="page"><PageHeader kicker="Полевой контур" title="Технический контроль" description="ТС, одометр, остаток топлива и готовность к выпуску на линию."/><section className="metrics-grid metrics-grid--compact"><MetricCard icon="truck" label="ТС на контроле" value={String(items.length)} meta="на сегодня"/><MetricCard icon="check" label="Готовы к выпуску" value={String(ready)} tone="green" meta="без замечаний"/><MetricCard icon="warning" label="Заблокированы" value={String(blocked)} tone="amber" meta="нужно действие"/></section><section className="panel"><div className="panel__header"><div><span className="eyebrow">Очередь</span><h2>Технические отметки</h2></div></div><div className="technical-list">{items.map(item=>{const [label,tone]=statusMeta(item.status);return <Link to={`/mechanic/technical-control/${item.id}`} className="technical-row" key={item.id}><div className="technical-row__icon"><Icon name="wrench"/></div><div className="technical-row__main"><span>{item.vehicle}</span><strong>{item.regNumber}</strong><small>{item.linkedTrip?`Рейс ${item.linkedTrip}`:'Без назначенного рейса'} · {item.inspectedAt}</small></div><div className="technical-row__facts"><span><b>Одометр</b><em>{item.odometerKm.toLocaleString('ru-RU')} км</em></span><span><b>Топливо</b><em>{item.fuelLiters} / {item.tankLiters} л</em></span></div><SemanticStatusText label={label} tone={tone}/><span className="row-arrow"><Icon name="chevron"/></span></Link>})}</div></section></div>}
