import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const root=process.cwd();
const input=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8');
const result=ts.transpileModule(input,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,esModuleInterop:true}});
const m={exports:{}};
new Function('module','exports','require',result.outputText)(m,m.exports,createRequire(import.meta.url));
const body=renderToStaticMarkup(React.createElement(m.exports.default));
const css=fs.readFileSync(path.join(root,'src/styles.css'),'utf8');
const fit=`function fit(){document.documentElement.style.setProperty('--deck-scale',new URLSearchParams(location.search).has('native')?'1':String(Math.min(1,innerWidth/1920)))}fit();addEventListener('resize',fit)`;
const html=`<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="tms-deck" content="management-contour-v1"><title>Управленческий контур TMS — КП</title><style>${css}</style></head><body>${body}<script>${fit}</script></body></html>`;
fs.writeFileSync('preview.html',html);
fs.copyFileSync('public/TMS.svg','TMS.svg');
if(fs.existsSync('dist'))fs.writeFileSync('dist/preview.html',html);
console.log('Static editable-DOM preview generated from React source.');
