import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const css = fs.readFileSync(path.join(root, 'src/styles.css'), 'utf8');
let slides = fs.readFileSync(path.join(root, 'src/slides.html'), 'utf8');
const logo = fs.readFileSync(path.join(root,'public/TMS.svg')).toString('base64');
slides = slides.replaceAll('src="./TMS.svg"', `src="data:image/svg+xml;base64,${logo}"`);
const scaler = `function sizeDeck(){const n=new URLSearchParams(location.search).get('native')==='1';document.documentElement.style.setProperty('--deck-scale',n?'1':String(Math.min(1,innerWidth/1920)))}sizeDeck();addEventListener('resize',sizeDeck);`;
const html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Готовый SaaS-продукт TMS ASUB. Платящие клиенты. Маркетинг и масштабирование."><title>TMS ASUB — готовый SaaS, масштабирование продаж</title><style>${css}</style></head><body><main class="deck">${slides}</main><script>${scaler}</script></body></html>`;
fs.writeFileSync(path.join(root,'preview.html'),html);
console.log('Static presentation exported: 12 editable-DOM sections.');
